services:
  guest:
    image: "polinux/snmpd"
    volumes:
    - ./my_snmpd.conf:/etc/snmpd/snmpd.conf
    ports:
      - "161:161/udp"
    networks:
      network:
        ipv4_address: 10.5.0.5
    command:
      - "-c /etc/snmpd/snmpd.conf"

  guest2:
    image: "polinux/snmpd"
    volumes:
    - ./my_snmpd2.conf:/etc/snmpd/snmpd.conf
    ports:
      - "162:161/udp"
    networks:
      network:
        ipv4_address: 10.5.0.2
    command:
      - "-c /etc/snmpd/snmpd.conf"

  guest3:
    image: "polinux/snmpd"
    volumes:
    - ./my_snmpd3.conf:/etc/snmpd/snmpd.conf
    ports:
      - "163:161/udp"
    networks:
      network:
        ipv4_address: 10.5.0.3
    command:
      - "-c /etc/snmpd/snmpd.conf"

  front:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=manager:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - manager

  manager:
    build:
      context: flask
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo  

  mongo:
    image: mongo

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1